server:
  port: 8080
  servlet:
    context-path: /

spring:
  # todo 개발 DB 연결
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # show sql in console
    properties:
      hibernate:
        format_sql: ture
    open-in-view: false # 영속성 컨텍스트 생존 범위를 트랜잭션 범위로 한정

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


logging:
  level:
    org.hibernate.type: trace # binding value
    com.app: debug # todo 패키지 수정


# feign 설정
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

kakao:
  client-id: eb816c833be487a3c946c11f753794fd
  secret: dbBtKPyYRPkMhZFhBIWVV3tla80t7Fb8
  redirect-uri: http://localhost:8080/api/oauth/kakao/callback
  token-uri: https://kauth.kakao.com/oauth/token
  userinfo-uri: https://kapi.kakao.com/v2/user/me

jwt:
  secret-key: 12345678901234567890123456789012
  expiration-time: 360000